---
title: "The Story"
author: "Lakshmi Arbatti"
date: "Thursday, April 09, 2015"
output: pdf_document
---

# Data Simulation Project

## Title : Aerobic fitness, micronutrient status, and academic achievement in Indian school-aged children.


Reference Links : http://www.ncbi.nlm.nih.gov/pubmed/25806824

                  http://www.indiachildren.com/htwtc.htm
                  
                  http://www.aarogya.com/family-health/childrens-health
                  
                  http://www.unt.edu/rss/class/mike/5700/Code/R.html
                  
                  http://journals.plos.org/plosone/article?id=10.1371/journal.pone.0122487

## Abstract:


 Aerobic fitness has been shown to have several beneficial effects on child health. However, research on its 
 relationship with academic performance has been limited, particularly in developing countries and among 
 undernourished populations. This study examined the association between aerobic fitness and academic achievement 
 in clinically healthy but nutritionally compromised Indian school-aged children and assessed whether 
 micronutrient status affects this association. 273 participants, aged 7 to 10.5 years, were enrolled from 
 three primary schools in Bangalore, India. Data on participants' aerobic fitness (20-m shuttle test), 
 demographics, anthropometry, diet, physical activity, and micronutrient status were abstracted. School-wide 
 exam scores in mathematics and Kannada language served as indicators of academic performance and were 
 standardized by grade level. The strength of the fitness/achievement association was analyzed using 
 Spearman's rank correlation, multiple variable logistic regression, and multi-level models. Significant 
 positive correlations between aerobic capacity (VO2 peak) and academic scores in math and Kannada were 
 observed (P < 0.05). After standardizing scores across grade levels and adjusting for school, gender, 
 socioeconomic status, and weight status (BMI Z-score), children with greater aerobic 
 capacities (mL * kg-1 * min-1) had greater odds of scoring above average on math and 
 Kannada exams (OR=1.08, 95% CI: 1.02 to 1.15 and OR=1.11, 95% CI: 1.04 to 1.18, respectively). This association 
 remained significant after adjusting for micronutrient deficiencies. These findings provide preliminary evidence
 of a fitness/achievement association in Indian children. While the mechanisms by which aerobic fitness may be 
 linked to academic achievement require further investigation, the results suggest that educators and 
 policymakers should consider the adequacy of opportunities for physical activity and fitness in schools for 
 both their physical and potential academic benefits. 

